// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// partialCorQUICKSTOP
extern "C" SEXP partialCorQUICKSTOP(SEXP pin_x, SEXP pin_y, SEXP pobsCor, SEXP pGroupFactor, SEXP pGroupSize, SEXP pnumGroup, SEXP pMaxIter, SEXP pn, SEXP preq_alpha, SEXP ptolerance_par, SEXP plog_decision_boundary, SEXP pseed);
RcppExport SEXP _PharmacoGx_partialCorQUICKSTOP(SEXP pin_xSEXP, SEXP pin_ySEXP, SEXP pobsCorSEXP, SEXP pGroupFactorSEXP, SEXP pGroupSizeSEXP, SEXP pnumGroupSEXP, SEXP pMaxIterSEXP, SEXP pnSEXP, SEXP preq_alphaSEXP, SEXP ptolerance_parSEXP, SEXP plog_decision_boundarySEXP, SEXP pseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pin_x(pin_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pin_y(pin_ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type pobsCor(pobsCorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pGroupFactor(pGroupFactorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pGroupSize(pGroupSizeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pnumGroup(pnumGroupSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pMaxIter(pMaxIterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pn(pnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type preq_alpha(preq_alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ptolerance_par(ptolerance_parSEXP);
    Rcpp::traits::input_parameter< SEXP >::type plog_decision_boundary(plog_decision_boundarySEXP);
    Rcpp::traits::input_parameter< SEXP >::type pseed(pseedSEXP);
    rcpp_result_gen = Rcpp::wrap(partialCorQUICKSTOP(pin_x, pin_y, pobsCor, pGroupFactor, pGroupSize, pnumGroup, pMaxIter, pn, preq_alpha, ptolerance_par, plog_decision_boundary, pseed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PharmacoGx_partialCorQUICKSTOP", (DL_FUNC) &_PharmacoGx_partialCorQUICKSTOP, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_PharmacoGx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
